server:
  port: 8081
  address: localhost
  servlet:
    context-path: /wecmdb

spring:
  profiles:
    active: dev

plugins:
  pacakge-name: wecmdb
  wecmdb-server-url: http://localhost:9080/wecmdb
  
logging:
  level:
    root: INFO